//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CikanUrun
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Mal Grubu alaný gereklidir.")]
        [Display(Name = "Mal Grubu")]
        public int MaterialId { get; set; }
        [Required(ErrorMessage = "Ürün Çýkýþ Yeri alaný gereklidir.")]
        [Display(Name = "Ürün Çýkýþ Yeri")]
        public int DepoId { get; set; }
        public int UserId { get; set; }
        public int IslemKodu { get; set; }
        [Required(ErrorMessage = "Çýkýþ Tarihi alaný gereklidir.")]
        [Display(Name = "Çýkýþ Tarihi")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/M/yyyy}")]
        public System.DateTime CikisTarihi { get; set; }
        [Required(ErrorMessage = "Adet alaný gereklidir.")]
        [MaxLength(ErrorMessage = "Çýkan ürün adeti stok miktarýndan fazla olamaz.")]
        public int Adet { get; set; }
        [Required(ErrorMessage = "Sevk Yeri alaný gereklidir.")]
        [Display(Name = "Sevk Yeri")]
        public string SevkYeri { get; set; }
        public System.DateTime OlusTarih { get; set; }
        public Nullable<System.DateTime> DegisTarih { get; set; }
        public bool Status { get; set; }

        public virtual Depo Depo { get; set; }
        public virtual Material Material { get; set; }
        public virtual User User { get; set; }
    }
}
