//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.CikanUrun = new HashSet<CikanUrun>();
            this.GirenUrun = new HashSet<GirenUrun>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Mal Grubu alaný gereklidir.")]
        [Display(Name = "Mal Grubu")]
        public string MaterialName { get; set; }
        public System.DateTime OlusTarih { get; set; }
        public Nullable<System.DateTime> DegisTarih { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CikanUrun> CikanUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GirenUrun> GirenUrun { get; set; }
        public virtual User User { get; set; }
    }
}
