//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockControlEntities : DbContext
    {
        public StockControlEntities()
            : base("name=StockControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<CikanUrun> CikanUrun { get; set; }
        public virtual DbSet<Depo> Depo { get; set; }
        public virtual DbSet<GirenUrun> GirenUrun { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Satıcı> Satıcı { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
