//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CikanUrun = new HashSet<CikanUrun>();
            this.GirenUrun = new HashSet<GirenUrun>();
            this.Material = new HashSet<Material>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý alaný gereklidir.")]
        [Display(Name = "Kullanýcý Adý")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Þifre alaný gereklidir.")]
        [Display(Name = "Þifre")]
        public string Password { get; set; }
        public string Departman { get; set; }
        public string Role { get; set; }
        public System.DateTime OlusTarih { get; set; }
        public Nullable<System.DateTime> DegisTarih { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CikanUrun> CikanUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GirenUrun> GirenUrun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
